/**
 * The scenario: two tenants, three roles, four endpoints.
 *
 * The observations are written by hand, not derived from the policy. If the
 * 'clean' set were generated by calling resolveExpected, the test for the
 * absence of discrepancies would check the function for consistency with itself
 * and would catch nothing.
 */

import type {
  AccessObservation,
  AccessOutcome,
  Account,
  Endpoint,
  ResolvedAccessPolicy,
} from "../../src/core/index.js";
import { ANY } from "../../src/core/index.js";

export const endpoints: readonly Endpoint[] = [
  { id: "ep.profile.read", method: "GET", path: "/v1/players/{playerId}" },
  { id: "ep.wallet.read", method: "GET", path: "/v1/players/{playerId}/wallet" },
  { id: "ep.tickets.list", method: "GET", path: "/v1/support/tickets" },
  { id: "ep.users.list", method: "GET", path: "/v1/admin/users" },
];

export const accounts: readonly Account[] = [
  { id: "acc.player.a", roleId: "player", tenantId: "tenant-a" },
  { id: "acc.support.a", roleId: "support", tenantId: "tenant-a" },
  { id: "acc.admin.a", roleId: "admin", tenantId: "tenant-a" },
  { id: "acc.player.b", roleId: "player", tenantId: "tenant-b" },
];

/**
 * The declared intent.
 *
 * The order of the rules matters: the last one that matches wins, so the broad
 * rule for admin comes after the narrow ones.
 */
export const policy: ResolvedAccessPolicy = {
  fallback: "denied",
  rules: [
    { roles: ANY, endpoints: ["ep.profile.read"], outcome: "allowed" },
    { roles: ["player"], endpoints: ["ep.wallet.read"], outcome: "allowed" },
    { roles: ["support"], endpoints: ["ep.tickets.list"], outcome: "allowed" },
    { roles: ["admin"], endpoints: ANY, outcome: "allowed" },
  ],
};

const STATUS_BY_OUTCOME: Readonly<Record<AccessOutcome, number>> = {
  allowed: 200,
  denied: 403,
  "not-found": 404,
  error: 0,
};

export function observe(
  accountId: string,
  endpointId: string,
  outcome: AccessOutcome,
): AccessObservation {
  return {
    accountId,
    endpointId,
    status: STATUS_BY_OUTCOME[outcome],
    headers: { "content-type": "application/json" },
    outcome,
    durationMs: 12,
  };
}

type Row = readonly [accountId: string, endpointId: string, outcome: AccessOutcome];

/** The platform behaves exactly as declared. There must be no discrepancies. */
const CLEAN: readonly Row[] = [
  ["acc.player.a", "ep.profile.read", "allowed"],
  ["acc.player.a", "ep.wallet.read", "allowed"],
  ["acc.player.a", "ep.tickets.list", "denied"],
  ["acc.player.a", "ep.users.list", "denied"],

  ["acc.support.a", "ep.profile.read", "allowed"],
  ["acc.support.a", "ep.wallet.read", "denied"],
  ["acc.support.a", "ep.tickets.list", "allowed"],
  ["acc.support.a", "ep.users.list", "denied"],

  ["acc.admin.a", "ep.profile.read", "allowed"],
  ["acc.admin.a", "ep.wallet.read", "allowed"],
  ["acc.admin.a", "ep.tickets.list", "allowed"],
  ["acc.admin.a", "ep.users.list", "allowed"],

  ["acc.player.b", "ep.profile.read", "allowed"],
  ["acc.player.b", "ep.wallet.read", "allowed"],
  ["acc.player.b", "ep.tickets.list", "denied"],
  ["acc.player.b", "ep.users.list", "denied"],
];

function toObservations(rows: readonly Row[]): readonly AccessObservation[] {
  return rows.map(([accountId, endpointId, outcome]) => observe(accountId, endpointId, outcome));
}

export const cleanObservations = toObservations(CLEAN);

function replace(rows: readonly Row[], patch: Row): readonly Row[] {
  return rows.map((row) => (row[0] === patch[0] && row[1] === patch[1] ? patch : row));
}

/** A player reaches the administrative list of users. */
export const escalationObservations = toObservations(
  replace(CLEAN, ["acc.player.a", "ep.users.list", "allowed"]),
);

/** Support is denied where access is declared. */
export const denialObservations = toObservations(
  replace(CLEAN, ["acc.support.a", "ep.tickets.list", "denied"]),
);
